### PR TITLE
Add test for usort

### PR DESCRIPTION
**Pull request by fmoletta**
Depends on #59

### CODE REVIEW

**Comment by HermanObst** [comment]
[Test common library hints USORT](https://trello.com/c/fzMqx67N/28-test-common-library-hints-usort)

**Review by pefontana — APPROVED** [review]

**Review by pefontana — CHANGES_REQUESTED** [review]
Nice one!
The test looks great.
When I run the hints_tests.py test, this program returns the error `ValueError: Custom Hint Error: NameError: name 'positions_dict' is not defined`
Just comment the test and we will be good to go

**Comment by fmoletta** [comment]
> Nice one!
> The test looks great.
> When I run the hints_tests.py test, this program returns the error `ValueError: Custom Hint Error: NameError: name 'positions_dict' is not defined`
> Just comment the test and we will be good to go

A fix was merged yesterday to fix this error. The test should be passing now, have you updated the compiled cairo-rs-py module before running the test?

**Review by Juan-M-V — APPROVED** [review]

**Comment by pefontana** [comment]
> > Nice one!
> > The test looks great.
> > When I run the hints_tests.py test, this program returns the error `ValueError: Custom Hint Error: NameError: name 'positions_dict' is not defined`
> > Just comment the test and we will be good to go
> 
> A fix was merged yesterday to fix this error. The test should be passing now, have you updated the compiled cairo-rs-py module before running the test?

Oh nice, I forgot to run maturin develop!

**Pull request merged**
