### PR TITLE
Make `CairoRunner::get_execution_resources()` publicly available.

### PR DESCRIPTION
**Pull request by azteca1998**

### CODE REVIEW

**Comment by azteca1998** [comment]
[add and export get_execution_resources() to PyCairoRunner](https://trello.com/c/vgWvsMdS/8-add-and-export-getexecutionresources-to-pycairorunner)

**Review by Oppen — APPROVED** [review]

**Comment by Oppen** [comment]
We should add some tests just to make the (future) coverage happy.

**Comment by azteca1998** [comment]
We should wait until the PR from `cairo-rs` is merged so that the pinned version on `Cargo.toml` can be updated accordingly to avoid problems with CI down the line.

**Review by Oppen — APPROVED** [review]

**Review by Juan-M-V — APPROVED** [review]

**Review by juanbono — APPROVED** [review]
LGTM Please remember to update the reference to the cairo-rs branch if needed.

**Pull request merged**
