### PR TITLE
Make `CairoRunner::mark_as_accessed` publicly available.

### PR DESCRIPTION
**Pull request by azteca1998**

### CODE REVIEW

**Comment by azteca1998** [comment]
[add mark_as_accessed to PyCairoRunner](https://trello.com/c/tXfCSZB1/7-add-markasaccessed-to-pycairorunner)

**Review by Oppen — APPROVED** [review]

**Comment by azteca1998** [comment]
The thing with adding tests from `cairo-rs-py` is that (as for right now) it's impossible to test anything effectively since it requires modifying an internal field (`vm.accessed_addresses`, see [this test](https://github.com/lambdaclass/cairo-rs/pull/501/files#diff-f683f40f725164315a627471b6a7d60c1024f247bb1e8c53cf537ae50057c725R2289)).

Because the compiler makes all fields public for the types in the same crate, the method can be tested no problem within `cairo-rs`, but at the same time makes it impossible to test outside from it.

**Comment by Oppen** [comment]
Fair enough.

**Comment by azteca1998** [comment]
[This PR](https://github.com/lambdaclass/cairo-rs/pull/507) will make it possible to test this method from `cairo-rs-py` since it modifies the relevant field.
If tests must be added, then I could add them after that PR is merged.

**Review by Juan-M-V — APPROVED** [review]

**Pull request merged**
