### PR TITLE
Remove `.unwrap()` from cairo struct implementation.

### PR DESCRIPTION
**Pull request by azteca1998**
Depends on [this PR](https://github.com/lambdaclass/cairo-rs/pull/514) on `cairo-rs`.

### CODE REVIEW

**Comment by azteca1998** [comment]
[remove unwrap](https://trello.com/c/OBiE6YMa/47-remove-unwrap)

**Review by Juan-M-V — APPROVED** [review]

**Comment by azteca1998** [comment]
We should wait until the PR from `cairo-rs` is merged so that the pinned version on `Cargo.toml` can be updated accordingly to avoid problems with CI down the line.

**Review by fmoletta — CHANGES_REQUESTED** [review]
PR merged in cairo-rs :)
Please update cairo version in toml

**Comment by azteca1998** [comment]
Fixed.

**Review by entropidelic — APPROVED** [review]

**Pull request merged**
